### PR TITLE
Add Dependabot configuration

### PR DESCRIPTION
**Pull request by widhalmt**
We need to keep an eye on deprecating GitHub actions. This should help.

### CODE REVIEW

**Comment by widhalmt** [comment]
I guess, we need #15 merged before this can work, right? Is that why you made the other PR, @afeefghannam89 ?

**Review by RincewindsHat — APPROVED** [review]
Looks good to me

**Comment by afeefghannam89** [comment]
> I guess, we need #15 merged before this can work, right? Is that why you made the other PR, @afeefghannam89 ?

yes, you are right.

**Review by afeefghannam89 — APPROVED** [review]
It looks good.

**Pull request merged**
