### PR TITLE
Config tweaks

### LINKED ISSUE #11: Daemonize variable is not used in systemd service file
In the systemd service file template (i.e., `templates/redis.service.j2`) the `redis_daemonize` variable is not used. But instead, daemonize is disabled and supervised is set to `systemd`.

Therefore and since the systemd service file takes precedence over the Redis server config, setting the variable `redis_daemonize` to `yes` has no effect.

### PR DESCRIPTION
**Pull request by tbumke**
Resolves #11 and #12 .

### CODE REVIEW

**Comment by tbumke** [comment]
Ansible role works but there seems to be an issue with Molecule. Probably related to: https://github.com/ansible-community/molecule/issues/3903.

**Comment by martialblog** [comment]
Looks alright to me, but I don't know why the commit 2eacec6 is in this PR. You might want to rebase this branch a bit.

**Comment by tbumke** [comment]
Updated my fork and now the duplicate commit should be removed from this PR. Still don't understand why Molecule fails... What I can say is, the same config works if there is no `ansible-lint` installed. Somehow Molecule's and Ansible Lint's dependencies are interfering with one another.

**Comment by martialblog** [comment]
@afeefghannam89 Can you have a look at this please?

**Comment by afeefghannam89** [comment]
@tbumke thanks for your PR, I will merge it and open an issue for the CI/CD problem

**Pull request merged**
